// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_time(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_rng_state(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// malariasimple_deterministic.cpp
SEXP dust2_system_malariasimple_deterministic_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_time(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_rng_state(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_unfilter_malariasimple_deterministic_DHSlink_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads);
extern "C" SEXP _malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_malariasimple_deterministic_DHSlink_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_filter_malariasimple_deterministic_DHSlink_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads, SEXP r_seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_DHSlink_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_system_malariasimple_deterministic_DHSlink_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_DHSlink_compare_data(SEXP ptr, SEXP r_data, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_DHSlink_compare_data(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_unfilter_malariasimple_deterministic_DHSlink_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_malariasimple_deterministic_DHSlink_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_unfilter_malariasimple_deterministic_DHSlink_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_history, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_run(SEXP ptr, SEXP r_initial, SEXP save_history, SEXP adjoint, SEXP r_index_state, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_malariasimple_deterministic_DHSlink_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_history), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_unfilter_malariasimple_deterministic_DHSlink_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_malariasimple_deterministic_DHSlink_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_unfilter_malariasimple_deterministic_DHSlink_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_malariasimple_deterministic_DHSlink_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_filter_malariasimple_deterministic_DHSlink_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_DHSlink_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_filter_malariasimple_deterministic_DHSlink_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_history, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_run(SEXP ptr, SEXP r_initial, SEXP save_history, SEXP adjoint, SEXP index_state, SEXP index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_DHSlink_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_history), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_filter_malariasimple_deterministic_DHSlink_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_DHSlink_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_filter_malariasimple_deterministic_DHSlink_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_DHSlink_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_filter_malariasimple_deterministic_DHSlink_rng_state(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_DHSlink_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic_DHSlink.cpp
SEXP dust2_filter_malariasimple_deterministic_DHSlink_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_DHSlink_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_time(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_rng_state(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_unfilter_malariasimple_deterministic_datalink_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads);
extern "C" SEXP _malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_malariasimple_deterministic_datalink_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_filter_malariasimple_deterministic_datalink_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_datalink_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads, SEXP r_seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_datalink_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_system_malariasimple_deterministic_datalink_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_deterministic_datalink_compare_data(SEXP ptr, SEXP r_data, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_deterministic_datalink_compare_data(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_unfilter_malariasimple_deterministic_datalink_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_malariasimple_deterministic_datalink_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_unfilter_malariasimple_deterministic_datalink_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_history, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_run(SEXP ptr, SEXP r_initial, SEXP save_history, SEXP adjoint, SEXP r_index_state, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_malariasimple_deterministic_datalink_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_history), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_unfilter_malariasimple_deterministic_datalink_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_malariasimple_deterministic_datalink_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_unfilter_malariasimple_deterministic_datalink_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_malariasimple_deterministic_datalink_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_filter_malariasimple_deterministic_datalink_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_datalink_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_datalink_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_filter_malariasimple_deterministic_datalink_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_history, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_datalink_run(SEXP ptr, SEXP r_initial, SEXP save_history, SEXP adjoint, SEXP index_state, SEXP index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_datalink_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_history), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_filter_malariasimple_deterministic_datalink_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_datalink_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_datalink_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_filter_malariasimple_deterministic_datalink_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_datalink_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_datalink_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_filter_malariasimple_deterministic_datalink_rng_state(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_datalink_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_datalink_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_deterministic_datalink.cpp
SEXP dust2_filter_malariasimple_deterministic_datalink_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _malariasimple_dust2_filter_malariasimple_deterministic_datalink_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_malariasimple_deterministic_datalink_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_time(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_rng_state(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// malariasimple_stochastic.cpp
SEXP dust2_system_malariasimple_stochastic_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_malariasimple_stochastic_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_malariasimple_stochastic_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_time(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_rng_state(cpp11::sexp ptr);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// stochastic_test.cpp
SEXP dust2_system_stochastic_test_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _malariasimple_dust2_system_stochastic_test_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_stochastic_test_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_alloc",                (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_alloc,                9},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_last_state",           (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_last_state,           4},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_last_trajectories",    (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_last_trajectories,    4},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_rng_state",            (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_rng_state,            1},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_run",                  (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_run,                  8},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_set_rng_state",        (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_set_rng_state,        2},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_update_pars",          (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_DHSlink_update_pars,          3},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_datalink_alloc",               (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_datalink_alloc,               9},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_datalink_last_state",          (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_datalink_last_state,          4},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_datalink_last_trajectories",   (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_datalink_last_trajectories,   4},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_datalink_rng_state",           (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_datalink_rng_state,           1},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_datalink_run",                 (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_datalink_run,                 8},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_datalink_set_rng_state",       (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_datalink_set_rng_state,       2},
    {"_malariasimple_dust2_filter_malariasimple_deterministic_datalink_update_pars",         (DL_FUNC) &_malariasimple_dust2_filter_malariasimple_deterministic_datalink_update_pars,         3},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_alloc",                (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_alloc,                8},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_compare_data",         (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_compare_data,         4},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_reorder",              (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_reorder,              2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_rng_state",            (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_rng_state,            1},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_run_to_time",          (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_run_to_time,          2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_rng_state",        (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_rng_state,        2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_state",            (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_state,            2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_state_initial",    (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_state_initial,    1},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_time",             (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_set_time,             2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_simulate",             (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_simulate,             5},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_state",                (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_state,                6},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_time",                 (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_time,                 1},
    {"_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_update_pars",          (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_DHSlink_update_pars,          2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_alloc",                        (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_alloc,                        8},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_alloc",               (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_alloc,               8},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_compare_data",        (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_compare_data,        4},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_reorder",             (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_reorder,             2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_rng_state",           (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_rng_state,           1},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_run_to_time",         (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_run_to_time,         2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_set_rng_state",       (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_set_rng_state,       2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_set_state",           (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_set_state,           2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_set_state_initial",   (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_set_state_initial,   1},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_set_time",            (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_set_time,            2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_simulate",            (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_simulate,            5},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_state",               (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_state,               6},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_time",                (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_time,                1},
    {"_malariasimple_dust2_system_malariasimple_deterministic_datalink_update_pars",         (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_datalink_update_pars,         2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_reorder",                      (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_reorder,                      2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_rng_state",                    (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_rng_state,                    1},
    {"_malariasimple_dust2_system_malariasimple_deterministic_run_to_time",                  (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_run_to_time,                  2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_set_rng_state",                (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_set_rng_state,                2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_set_state",                    (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_set_state,                    2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_set_state_initial",            (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_set_state_initial,            1},
    {"_malariasimple_dust2_system_malariasimple_deterministic_set_time",                     (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_set_time,                     2},
    {"_malariasimple_dust2_system_malariasimple_deterministic_simulate",                     (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_simulate,                     5},
    {"_malariasimple_dust2_system_malariasimple_deterministic_state",                        (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_state,                        6},
    {"_malariasimple_dust2_system_malariasimple_deterministic_time",                         (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_time,                         1},
    {"_malariasimple_dust2_system_malariasimple_deterministic_update_pars",                  (DL_FUNC) &_malariasimple_dust2_system_malariasimple_deterministic_update_pars,                  2},
    {"_malariasimple_dust2_system_malariasimple_stochastic_alloc",                           (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_alloc,                           8},
    {"_malariasimple_dust2_system_malariasimple_stochastic_reorder",                         (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_reorder,                         2},
    {"_malariasimple_dust2_system_malariasimple_stochastic_rng_state",                       (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_rng_state,                       1},
    {"_malariasimple_dust2_system_malariasimple_stochastic_run_to_time",                     (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_run_to_time,                     2},
    {"_malariasimple_dust2_system_malariasimple_stochastic_set_rng_state",                   (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_set_rng_state,                   2},
    {"_malariasimple_dust2_system_malariasimple_stochastic_set_state",                       (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_set_state,                       2},
    {"_malariasimple_dust2_system_malariasimple_stochastic_set_state_initial",               (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_set_state_initial,               1},
    {"_malariasimple_dust2_system_malariasimple_stochastic_set_time",                        (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_set_time,                        2},
    {"_malariasimple_dust2_system_malariasimple_stochastic_simulate",                        (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_simulate,                        5},
    {"_malariasimple_dust2_system_malariasimple_stochastic_state",                           (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_state,                           6},
    {"_malariasimple_dust2_system_malariasimple_stochastic_time",                            (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_time,                            1},
    {"_malariasimple_dust2_system_malariasimple_stochastic_update_pars",                     (DL_FUNC) &_malariasimple_dust2_system_malariasimple_stochastic_update_pars,                     2},
    {"_malariasimple_dust2_system_stochastic_test_alloc",                                    (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_alloc,                                    8},
    {"_malariasimple_dust2_system_stochastic_test_reorder",                                  (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_reorder,                                  2},
    {"_malariasimple_dust2_system_stochastic_test_rng_state",                                (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_rng_state,                                1},
    {"_malariasimple_dust2_system_stochastic_test_run_to_time",                              (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_run_to_time,                              2},
    {"_malariasimple_dust2_system_stochastic_test_set_rng_state",                            (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_set_rng_state,                            2},
    {"_malariasimple_dust2_system_stochastic_test_set_state",                                (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_set_state,                                2},
    {"_malariasimple_dust2_system_stochastic_test_set_state_initial",                        (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_set_state_initial,                        1},
    {"_malariasimple_dust2_system_stochastic_test_set_time",                                 (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_set_time,                                 2},
    {"_malariasimple_dust2_system_stochastic_test_simulate",                                 (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_simulate,                                 5},
    {"_malariasimple_dust2_system_stochastic_test_state",                                    (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_state,                                    6},
    {"_malariasimple_dust2_system_stochastic_test_time",                                     (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_time,                                     1},
    {"_malariasimple_dust2_system_stochastic_test_update_pars",                              (DL_FUNC) &_malariasimple_dust2_system_stochastic_test_update_pars,                              2},
    {"_malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_alloc",              (DL_FUNC) &_malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_alloc,              8},
    {"_malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_last_state",         (DL_FUNC) &_malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_last_state,         4},
    {"_malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_last_trajectories",  (DL_FUNC) &_malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_last_trajectories,  4},
    {"_malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_run",                (DL_FUNC) &_malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_run,                8},
    {"_malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_update_pars",        (DL_FUNC) &_malariasimple_dust2_unfilter_malariasimple_deterministic_DHSlink_update_pars,        3},
    {"_malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_alloc",             (DL_FUNC) &_malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_alloc,             8},
    {"_malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_last_state",        (DL_FUNC) &_malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_last_state,        4},
    {"_malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_last_trajectories", (DL_FUNC) &_malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_last_trajectories, 4},
    {"_malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_run",               (DL_FUNC) &_malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_run,               8},
    {"_malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_update_pars",       (DL_FUNC) &_malariasimple_dust2_unfilter_malariasimple_deterministic_datalink_update_pars,       3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_malariasimple(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
